---
- name: Deploy Windows AD Instances on OpenStack
  hosts: localhost
  gather_facts: false
  connection: local
  become: false
  vars_files:
    - node-config/ad-node-openstack.yml
  vars:
    config_file: "{{ lookup('env', 'OS_CLIENT_CONFIG_FILE') }}"
    ansible_port: 5986
    windows: true
  roles:
    - role: ansible-role-os-stack
      role_action: deprovision
