---
- name: remove computer objects
  hosts: all
  gather_facts: true
  serial: 1

  pre_tasks:
    - debug:
        msg: "{{ ansible_hostname | default('') }}"
  roles:
    - role: ad-computer-registration
      role_action: deregister
      computer_name: "{{ ansible_hostname }}"
      delegate_to: "{{ windows_ad_server_ip }}"
      when: ansible_hostname is defined

- name: remove cluster object
  hosts: all
  gather_facts: false
  vars:
    ansible_port: 5986
    ansible_connection: winrm
    ansible_winrm_transport: credssp
    ansible_winrm_server_cert_validation: ignore
  roles:
    - role: ad-computer-registration
      role_action: deregister
      computer_name: "{{ cluster_name }}"
      delegate_to: "{{ windows_ad_server_ip }}"
      run_once: true
