---
- name: Remove Windows Cluster Servers
  hosts: all
  gather_facts: false
  connection: local
  become: false
  vars_files:
    - node-config/cluster-nodes-vmware.yml

  roles:
    - role: ansible-role-vmware
      role_action: deprovision
      delegate_to: localhost
