---
- name: Deploy Windows Cluster Servers
  hosts: all
  gather_facts: false
  connection: local
  become: false

  vars_files:
    - node-config/cluster-nodes-vmware.yml

  roles:
    - ansible-role-vmware
