---
- name: SQL 2016 Create DB with Script
  hosts: all
  vars:
    login_user: "{{ mssql_username }}"
    login_password: "{{ mssql_password }}"
    instance_name: "{{ ansible_hostname }}"
  roles:
    - sql_create_db_with_script
