---
- name: SQL 2016 Create DB with Script
  hosts: all
  vars:
    login_user: sa
    login_password: "{{ mssql_password }}"
    instance_name: "{{ ansible_hostname }}"

  roles:
    - sql_run_sql_script
