---
- name: windows change tcpip parameters
  hosts: all

  tasks:
    - name: change tcpip parameter
      win_regedit:
        path: HKLM:\SYSTEM\CurrentControlSet\Services\Tcpip\Parameters
        name: EnablePMTUDiscovery
        data: 1
        type: dword

    - name: change tcpip parameter
      win_regedit:
        path: HKLM:\SYSTEM\CurrentControlSet\Services\Tcpip\Parameters
        name: EnablePMTUBHDetect
        data: 1
        type: dword

    - name: get interfaces
      win_reg_stat:
        path: HKLM:\SYSTEM\CurrentControlSet\Services\Tcpip\Parameters\Interfaces\
      register: interface_ids

    - debug:
        var: interface_ids

    - name: set mtu size
      win_regedit:
        path: HKLM:\SYSTEM\CurrentControlSet\Services\Tcpip\Parameters\Interfaces\{{ item }}
        name: MTU
        data: 4096
        type: dword
      loop: "{{ interface_ids.sub_keys }}"
#
#    - name: change mtu
#      win_shell: change_mtu 4096 {{ interface_name }}
