---
- name: Windows Patches
  hosts: all
  vars:
    categories:
      - SecurityUpdates
      - CriticalUpdates
  tasks:
    - block:
        - name: apply windows updates
          win_updates:
            category_name: "{{ categories | default([]) }}"
            blacklist: "{{ blacklist | default([]) }}"
            whitelist: "{{ whitelist | default([]) }}"
            reboot: false
          register: patching_output

        - name: reboot if necessary
          win_reboot:
          when:
            - patching_output.reboot_required
            - reboot_method == 'auto'
            - patch_window == reboot_window

        - name: check missing updates
          win_updates:
            category_name: "{{ categories | default([]) }}"
            state: searched
          register: missing_output

        - name: warn if missed updates
          debug:
            msg: "Yo yo yo - We missed some ( {{ missing_output.found_update_count }} updates ) "
          when:
            - missing_output.found_update_count is defined
            - missing_output.found_update_count > 0

        - name: list of updates not installed (skipped)
          debug:
            msg: "{{ item }}"
          loop:
            - "{{ missing_output.updates }}"
          when:
            - missing_output.found_update_count is defined
            - missing_output.found_update_count > 0
            - missing_output.updates is defined
      when:
        - patch_enabled
        - patch_method == 'auto'
