---
- name: Install SQL Server Management Studio
  hosts: all

  tasks:
    - name: Install SQL Server Management Studio
      win_chocolatey:
        name: sql-server-management-studio
        state: latest
