---
- name: Deploy Windows Instances on OpenStack
  hosts: localhost
  gather_facts: false
  connection: local
  become: false
  vars_files:
    - win-nodes-openstack.yml
  vars:
    config_file: "{{ lookup('env', 'OS_CLIENT_CONFIG_FILE') }}"
    ansible_port: 5986
    windows: true
  roles:
    - ansible-role-os-stack
