---
- name: Deploy Windows Instances on ec2
  hosts: localhost
  gather_facts: false
  connection: local
  become: false
  vars_files:
    - win-nodes-ec2.yml
  vars:
    ansible_port: 5986
    windows: true
  roles:
    - ec2-find-amis
    - ansible-role-ec2
