---
- name: add a powershell module
  win_psmodule:
    name: xActiveDirectory
    state: present

- name: add computer object
  win_dsc:
    resource_name: xADComputer
    ComputerName: "{{ computer_name }}"
    Path: '{{ join_ou_path | default("") }}'
    Ensure: Present
  when:
    - computer_name is defined
