---
- name: copy log file
  win_copy:
    src: "{{ log_file }}"
    dest: "{{ smb_share }}\\{{ destination_file_location }}\\{{ ansible_host }}_mcafee_log.txt"
    remote_src: true
  become: true
  become_method: runas
  become_flags: logon_type=new_credentials logon_flags=netcredentials_only
  vars:
    ansible_become_user: "{{ smb_share_username }}"
    ansible_become_pass: "{{ smb_share_password }}"
